In [2]:
import numpy as np

In [2]:
#1.Create a NumPy array from a python list
list1=[1,2,3,4]
l_to_array=np.array(list1)
print(l_to_array)
type(l_to_array)

[1 2 3 4]


numpy.ndarray

In [3]:
#2.Print the type of the array created above
list1=[1,2,3,4]
l_to_array=np.array(list1)
type(l_to_array)

numpy.ndarray

In [4]:
#3.Create a NumPy array from a python list of lists
list_1=[[1,2,3],[4,5,6]]
np.array(list_1)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
#4.Print the type of the array created above
type(np.array(list_1))

numpy.ndarray

In [6]:
#5.While creating the numpy array, specify the data type as float32.
a = [[1,2,3], [4,5,6]]

np_array =np.array(a).astype("float32")
print(np_array)
np_array.dtype

[[1. 2. 3.]
 [4. 5. 6.]]


dtype('float32')

In [15]:
#6.Create a NumPy array of Zeros
np_array = np.zeros((3,3))
print(np_array)
type(np_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


numpy.ndarray

In [19]:
#7.Create a multi-dimensional NumPy array of Zeros
np_array = np.zeros((3,3,1))
print(np_array.ndim)
np_array

3


array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [22]:
#8.Create a NumPy array of Ones
arr_=np.ones((3,3)).astype("int32")
arr_

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [23]:
#9.Create a multi-dimensional NumPy array of Ones
arr_=np.ones((3,3,1)).astype("int32")
arr_

array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]], dtype=int32)

In [26]:
#10.Create an Identity Numpy Array of order 3
arr=np.identity(3).astype("int8")
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [3]:
#11-13.Create an equally spaced Numpy Array with a specific step
'''Generate values from start=0 to stop=10 with step=1:'''
np.arange(0,11,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#Generate values from start=5to stop=11 with step=1:
np.arange(5,12,1)

array([ 5,  6,  7,  8,  9, 10, 11])

In [6]:
#Generate values start=5 to step=11 with step=2.
np.arange(5,11,2)

array([5, 7, 9])

In [8]:
#14-15.Create an equally spaced Numpy Array with a specific array size.
'''Generate a numpy array of size 5 with start=0 to stop=10'''
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
#Generate a numpy array of size 5 with start=5 to stop=7
np.linspace(5,7,5)

array([5. , 5.5, 6. , 6.5, 7. ])

In [3]:
#Generate a random integer array of size 5 with start=0 to stop=10
np.random.randint(0,10,5)

array([2, 5, 9, 3, 8])

In [6]:
#Generate a random float array of size 10
np.random.rand(10)

array([0.34559984, 0.21368131, 0.64862974, 0.2135445 , 0.34222321,
       0.12063526, 0.79128799, 0.16600988, 0.06666089, 0.97808601])

In [13]:
#18-19.Generate NumPy Array from a Pandas Series using two methods
#Method_1
s = pd.Series([1,2,3,4], name = "col")

np_array =np.asarray(s)
print(np_array)

[1 2 3 4]


In [14]:
#Method_2
s = pd.Series([1,2,3,4], name = "col")

np_array = np.asarray(s)
print(np_array)

[1 2 3 4]


In [21]:
#20-21.Shape of the NumPy Array in two ways
#Method_1
a = np.ones((2, 3))

shape_of_a = np.reshape(a,(6,1))
print("a=",a)
print()
print(shape_of_a)

a= [[1. 1. 1.]
 [1. 1. 1.]]

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [22]:
#20-21.Shape of the NumPy Array in two ways
#Method_2
a = np.ones((2, 3))

shape_of_a = np.reshape(a,(3,2))
print("a=",a)
print()
print(shape_of_a)

a= [[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
#22.Reshape the NumPy Array to 2*5
arr_22=np.linspace(1,20,10)
arr_2_by_5=np.reshape(arr_22,(2,5))
print(arr_2_by_5)
print(arr_2_by_5.shape)

[[ 1.          3.11111111  5.22222222  7.33333333  9.44444444]
 [11.55555556 13.66666667 15.77777778 17.88888889 20.        ]]
(2, 5)


In [24]:
#23-24.Transpose the NumPy Array in two ways.
arr_23=np.reshape(np.random.randint(2,20,6),(2,3))
#Way_1
Transpose_1=arr_23.T
#Way_2
Transpose_2=np.transpose(arr_23)
print("Array:")
print(arr_23)
print()
print("Transpose_1:")
print(Transpose_1)
print()
print("Transpose_2:")
print(Transpose_2)

Array:
[[19 17  4]
 [ 3 11  2]]

Transpose_1:
[[19  3]
 [17 11]
 [ 4  2]]

Transpose_2:
[[19  3]
 [17 11]
 [ 4  2]]


In [2]:
#25-27.Concatenate multiple NumPy arrays to form one NumPy Array

In [29]:
#Concatenate row-wise
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np_array_row =np.concatenate((a,b),axis=0) #Axis=0 for row wise
print(np_array)

[[1 2]
 [3 4]
 [5 6]]


In [32]:
#Concatenate column-wise
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
#
np_array_column =np.concatenate((a,b.T),axis=1) #Axis=1 for column wise(b.T=make sure the no. of rows are equal)
print(np_array_column)

[[1 2 5]
 [3 4 6]]


In [33]:
#Concatenate to generate a flat NumPy Array
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np_array =np.concatenate((a,b),axis=None) #Axis=None for Flat
print(np_array)

[1 2 3 4 5 6]


In [35]:
#28-29. Concatenate using vstack() and hstack()
#vstack()
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np_array = np.vstack((a,b))
print(np_array)

[[1 2]
 [3 4]
 [5 6]]


In [38]:
#hstack
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np_array = np.hstack((a,b.T))
print(np_array)

[[1 2 5]
 [3 4 6]]


In [39]:
#30. Flatten NumPy Array
a = np.array([[1,2], [3,4]])

Flat_arr =a.flatten()
print(Flat_arr)

[1 2 3 4]


In [41]:
#31-33. Print Unique Elements of a NumPy Array
a = np.array([[1,2], [3,2]])

Unique_elements = np.unique(a)
print(Unique_elements)

[1 2 3]


In [44]:
#return unique rows
a = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

Unique_rows =np.unique(a,axis=0) #Axis=0 for unique Rows
print(Unique_rows)

[[1 2 3]
 [2 3 4]]


In [46]:
#return unique columns
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])

Unique_columns=np.unique(a,axis=1) #Axis=1, for unique columns
print(Unique_columns)

[[1 3]
 [1 3]
 [1 4]]


In [48]:
#34.Squeeze the NumPy Array
a = np.array([[[0], [1], [2]]])

Squeezed_Arr =np.squeeze(a)
print(Squeezed_Arr)

[0 1 2]


In [51]:
#35.Get Python list from NumPy array.
arr = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])

py_list =arr.tolist()
print(py_list)

[[1, 1, 3], [1, 1, 3], [1, 1, 4]]


In [4]:
#36. Add two numpy arrays element-wise
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array =a+b
print(np_array)

[[2 3 6]
 [2 3 6]
 [3 4 8]]


In [5]:
#37. Multiple two numpy arrays element-wise
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = a*b
print(np_array)

[[ 1  2  9]
 [ 1  2  9]
 [ 2  3 16]]


In [6]:
#38. Subtract two numpy arrays element-wise
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = a-b
print(np_array)

[[ 0 -1  0]
 [ 0 -1  0]
 [-1 -2  0]]


In [7]:
#39. Divide two numpy arrays element-wise
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = a/b
print(np_array)

[[1.         0.5        1.        ]
 [1.         0.5        1.        ]
 [0.5        0.33333333 1.        ]]


In [14]:
#40-42. Trigonometric functions
x = np.array([1,2,3])

np_sin_x = np.sin(x).round(2)
np_cos_x = np.cos(x).round(2)
np_tan_x = np.tan(x).round(2)
print("np_sin_x:",np_sin_x)
print("np_tan_x:",np_tan_x)
print("np_cosn_x:",np_cos_x)

np_sin_x: [0.84 0.91 0.14]
np_tan_x: [ 1.56 -2.19 -0.14]
np_cosn_x: [ 0.54 -0.42 -0.99]


In [20]:
#43. Print the element-wise floor 
a = np.linspace(1, 2, 5)

np_array = np.floor(a)
print("Array:",a)
print("Floored:",np_array)

Array: [1.   1.25 1.5  1.75 2.  ]
Floored: [1. 1. 1. 1. 2.]


In [23]:
#44. Print the element-wise ceil
a = np.linspace(1, 2, 5)

np_array = np.ceil(a)
print("Array:",a)
print("Ceiled:",np_array)

Array: [1.   1.25 1.5  1.75 2.  ]
Ceiled: [1. 2. 2. 2. 2.]


In [24]:
#45.Print the element-wise nearest integer
a = np.linspace(1, 2, 5)

np_array = np.round(a)
print(np_array)

[1. 1. 2. 2. 2.]


In [25]:
#46.Round to given number of decimal places
a = np.linspace(1, 2, 7)
decimal_places = 2

np_array =np.round(a,2)
print(np_array)

[1.   1.17 1.33 1.5  1.67 1.83 2.  ]


In [26]:
#47.Calculate the element-wise exponential
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.exp(a)
print(np_array)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [27]:
#48. Calculate the element-wise exponential and round to two decimal places
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.exp(a).round(2)
print(np_array)

[  2.72   7.39  20.09  54.6  148.41]


In [28]:
#49. Calculate the element-wise natural logarithm 
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.log(a)
print(np_array)

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [29]:
#50. Calculate the element-wise natural logarithm and round to two decimal places
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.log(a).round(2)
print(np_array)

[0.   0.69 1.1  1.39 1.61]


In [30]:
#51.Calculate the element-wise logarithm at base 2
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.log2(a)
print(np_array)

[0.         1.         1.5849625  2.         2.32192809]


In [31]:
#52. Calculate the element-wise logarithm at base 2 and take floor of the result
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.floor(np.log2(a))
print(np_array)

[0. 1. 1. 2. 2.]


In [32]:
#53. Find the sum of numpy array elements
a = np.array([[1, 2], [3, 4]])

sum_of_array = np.sum(a)
print(sum_of_array)

10


In [33]:
#54. Find the row-wise sum of numpy array elements
a = np.array([[1, 2], [3, 4]])

sum_of_array = np.sum(a,axis=0)
print(sum_of_array)

[4 6]


In [34]:
#55. Find the column-wise sum of numpy array elements
a = np.array([[1, 2], [3, 4]])

sum_of_array = np.sum(a,axis=1)
print(sum_of_array)

[3 7]


In [36]:
#56. Calculate the product of array elements
a = np.array([[1, 2], [3, 4]])

prod_of_array = np.prod(a)
print(prod_of_array)

24


In [37]:
#57. Find the row-wise product of numpy array elements
a = np.array([[1, 2], [3, 4]])

prod_of_array = np.prod(a,axis=0)
print(prod_of_array)

[3 8]


In [38]:
#58. Find the column-wise product of numpy array element
a = np.array([[1, 2], [3, 4]])

prod_of_array = np.prod(a,axis=1)
print(prod_of_array)

[ 2 12]


In [39]:
#59. Compute the square root of array elements
a = np.array([[1, 2], [3, 4]])

np_array = np.sqrt(a)
print(np_array)

[[1.         1.41421356]
 [1.73205081 2.        ]]


### Matrix and Vector Operations

In [42]:
#60. Compute the dot product of two NumPy arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = np.dot(a,b)
print(np_array)

[[3 3]
 [7 7]]


In [45]:
#61.Compute the row-wise dot product of two NumPy arrays 
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = np.einsum("ij,ij->i",a,b)
print(np_array)

[3 7]


In [50]:
#62. Compute the matrix product of two NumPy arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = np.matmul(a,b)
print(np_array)

[[3 3]
 [7 7]]


In [51]:
#63. Compute the matrix product of two NumPy arrays using the @ operator
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = a@b
print(np_array)

[[3 3]
 [7 7]]


In [53]:
#64.Compute the length of the vector
a = np.arange(-4, 5)

vec_len = np.linalg.norm(a)
print(vec_len)

7.745966692414834


In [54]:
#65.Sort the array inplace row-wise
a = np.array([[1,4],[3,1]])

np_array = np.sort(a,axis=0)
print(np_array)

[[1 1]
 [3 4]]


In [55]:
#66. Sort the array inplace column-wise
a = np.array([[1,4],[3,1]])

np_array = np.sort(a,axis=1)
print(np_array)

[[1 4]
 [1 3]]


In [57]:
#67. Sort the flattened array
a = np.array([[1,4],[3,1]])

np_array = np.sort(a.flatten())
print(np_array)

[1 1 3 4]


In [58]:
#68. Order of Indices in a Sorted NumPy Array
a = np.array([3, 1, 2])

np_array = np.sort(a)
print(np_array)

[1 2 3]


In [64]:
#69-71. Find the index corresponding to the Maximum Values.
a = np.array([[15, 13, 10,  1, 18],
              [14, 19, 19, 17,  8]])

In [60]:
#69.In a flattened array:
Flat_array=np.argmax(a.flatten())
Flat_array

6

In [66]:
#70.Indices of max along column
max_col=np.argmax(a,axis=0)
max_col

array([0, 1, 1, 1, 0])

In [67]:
#71.Indices of max along row
max_col=np.argmax(a,axis=1)
max_col

array([4, 1])

## Find the index corresponding to the Minimum Values.


In [4]:
a = np.array([[15, 13, 10,  1, 18],
              [14, 19, 19, 17,  8]])

In [5]:
#72. In a flattened array
min_index=np.argmin(a.flatten())
print(min_index)

3


In [7]:
#73.Indices of min along column
min_index=np.argmin(a,axis=0)
print(min_index)

[1 0 0 0 1]


In [8]:
#74.Indices of min along row
min_index=np.argmin(a,axis=1)
print(min_index)

[3 4]


In [11]:
#75. Print the indices of non-zero elements
a = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])

non_zero_ind = np.nonzero(a)
print(non_zero_ind)

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))


In [13]:
#76. Find the mean of the whole numpy array
a = np.array([[1, 2], [3, 4]])

mean = np.mean(a)
print(mean)

2.5


In [14]:
#77. Find the mean of the numpy array along row-axis
a = np.array([[1, 2], [3, 4]])

mean = np.mean(a,axis=0)
print(mean)

[2. 3.]


In [15]:
#78. Find the mean of the numpy array along column-axis
a = np.array([[1, 2], [3, 4]])

mean = np.mean(a,axis=1)
print(mean)

[1.5 3.5]


In [16]:
#79. Find the median of the whole numpy array
a = np.array([[1, 2], [3, 4]])

median = np.median(a)
print(median)

2.5


In [17]:
#80. Find the median of the numpy array along row-axis
a = np.array([[1, 2], [3, 4]])

median = np.median(a,axis=0)
print(median)

[2. 3.]


In [19]:
#81. Find the median of the numpy array along columns-axis
a = np.array([[1, 2], [3, 4]])

median = np.median(a,axis=1)
print(median)

[1.5 3.5]


In [21]:
#82-84.Find the std dev of the whole numpy array
a = np.array([[1, 2], [3, 4]])

std_dev = np.std(a)
std_dev_row=np.std(a,axis=0)
std_dev_col=np.std(a,axis=1)
print("standard deveiation:",std_dev)
print("standard deveiation row:",std_dev_row)
print("standard deveiation column:",std_dev_col)

standard deveiation: 1.118033988749895
standard deveiation row: [1. 1.]
standard deveiation column: [0.5 0.5]


In [22]:
#Done with the Basic Functions of numpy till now...
"""For more such notes connect with "Govind Kumar" over LinkedIn..."""

'For more such notes connect with "Govind Kumar" over LinkedIn...'